#if !defined(DK_ECS_ID_H)
#define DK_ECS_ID_H

typedef enum {
  ENTITY_PLAYER,
  ENTITY_ENEMY,
  ENTITY_OBSTACLE,
  ENTITY_PLATFORM,
  ENTITY_PLATFORM2,
  ENTITY_COUNT
} ENTITY_ID;

typedef enum {
  COMPONENT_VELOCITY,
  COMPONENT_ACCELERATION,
  COMPONENT_POSITION,
  COMPONENT_SIZE,
  COMPONENT_RECT,
  COMPONENT_COUNT
} COMPONENT_ID;

#define ENTITY_ID_TO_STR(id) \
  (id == ENTITY_PLAYER) ? "PLAYER" : \
  (id == ENTITY_ENEMY) ? "ENEMY" : \
  (id == ENTITY_OBSTACLE) ? "OBSTACLE" : "UNKNOWN"

#define COMPONENT_ID_TO_STR(id) \
  (id == COMPONENT_VELOCITY) ? "VELOCITY" : \
  (id == COMPONENT_ACCELERATION) ? "ACCELERATION" : \
  (id == COMPONENT_POSITION) ? "POSITION" : "UNKNOWN" \
  (id == COMPONENT_SIZE) ? "SIZE" : "UNKNOWN"

#endif // DK_ECS_ID_H